# Generated by Django 2.2.5 on 2019-10-03 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='concentrationarea',
            table='concentration_areas',
        ),
    ]
